#
# HERMES2D
#

set(HERMES2D_NAME "hermes2d-real")

FIND_PATH(HERMES2D_INCLUDE_DIR hermes2d.h ${HERMES2D_SOURCE_ROOT} ${HERMES2D_ROOT}/include /usr/include /usr/include/umfpack /usr/local/include/UMFPACK /usr/include/suitesparse)
FIND_LIBRARY(HERMES2D_LIBRARY_RELEASE ${HERMES2D_NAME} ${HERMES2D_LIBRARY_ROOT} ${HERMES2D_ROOT}/lib /usr/lib64 /usr/lib /usr/local/lib64 /usr/local/lib)
FIND_LIBRARY(HERMES2D_LIBRARY_DEBUG "${HERMES2D_NAME}-debug" ${HERMES2D_LIBRARY_ROOT} ${HERMES2D_ROOT}/lib /usr/lib64 /usr/lib /usr/local/lib64 /usr/local/lib)

set(HERMES2D_LIBRARY "${HERMES2D_LIBRARY_RELEASE}")
if(DEBUG)
    set(HERMES2D_LIBRARY "${HERMES2D_LIBRARY_DEBUG}")
endif(DEBUG)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(HERMES2D DEFAULT_MSG HERMES2D_LIBRARY HERMES2D_INCLUDE_DIR)
