#
# HERMES_COMMON
#

set(PYTHON_SUBDIR python2.6)

FIND_PATH(PYTHON_INCLUDE_DIR Python.h /usr/include/${PYTHON_SUBDIR} /usr/local/include/${PYTHON_SUBDIR})
FIND_PATH(HERMES_COMMON_INCLUDE_DIR _hermes_common_api.h ${HERMES_COMMON_ROOT} ${HERMES2D_ROOT}/include /usr/include /usr/local/include)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(HERMES_COMMON DEFAULT_MSG HERMES_COMMON_INCLUDE_DIR PYTHON_INCLUDE_DIR)

